### ISSUE TITLE
Editing without save

### ISSUE THREAD

**Issue by Glazelf** [aymeric-giraudet/PKHeX.Web#3]
Feature Request: Allow to edit an empty save / make individual Pokémon files (and export them) without loading a save.

Usecase:
- Likely a huge help to people without the ability to export saves, like sysbot users.
- Could be good to quickly check something, especially on mobile without a save at hand.

**Comment by aymeric-giraudet** [comment]
Done with commit 24d03f1ecb1ea1f0af4af3fa83dbbf884661733f !
It was on my backlog but I wasn't sure on priorities, I should probably make a Project with a backlog sorted by priority 😄 

It works similarly to PKHeX, loads a blank Brilliant Diamond save by default, you can change the game you want in settings. Those settings will be saved on your browser local storage !
You can also open a .p(k|b)* file now, and export Pokémon.

Now I'm off to implement the rest of the Pokémon Editor !

**Comment by Glazelf** [comment]
Doesn't seem to reflect these changes yet, does it take a while for the webpage to be republished?
![image](https://user-images.githubusercontent.com/35176230/148831349-35a35dab-2900-480a-a953-ff8866cc67a7.png)

**Comment by aymeric-giraudet** [comment]
Ah yeah, you have to wait until the new service worker completely
installed, close the window then go on the app again.
It takes a while cause it redownloads all the assets :/ You can also delete
all site settings so it works.

I'm gonna have to implement a notification that says when a new update is
installed and to force cache invalidation 😅

**Comment by Glazelf** [comment]
> Ah yeah, you have to wait until the new service worker completely installed, close the window then go on the app again. It takes a while cause it redownloads all the assets :/ You can also delete all site settings so it works. I'm gonna have to implement a notification that says when a new update is installed and to force cache invalidation 😅  

Oh yeah haha Ctrl + F5 fixed it so I deleted my reply. Sorry for the confusion.
Looks great! :)
